# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ONE STEP LICENSING
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  your partner for increasing brand awareness, and revenue and driving customer loyalty.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %-d, %Y"
github_username: sabrymuhamad

# SEO
admin: "ONE STEP LICENSING"
admin_city: "Hong Kong" # used for SEO, see _includes/head.html
admin_state: "Hong Kong" # used for SEO, see _includes/head.html
share-image: "" # used for SEO, see _includes/_head.html

# Optional features
animated: true

menu:
  - title: "About"
    url: "/#about"
  - title: "Services"
    url: "/#services"
  - title: "Showcase"
    url: "/#showcase"
  - title: "Contact"
    url: "/#contact"

social_icons:
  - name: linkedin
    url: "https://www.linkedin.com/in/onestep-licensing-b67299221/"
    icon: "/assets/images/icon__linkedin.svg"
  - name: x
    url: "#"
    icon: "/assets/images/icon__x.svg"
  - name: whatsapp
    url: "https://wa.me/85267138400?text=I'm%20interested%20in%20ONESTEP%20LICENSING"
    icon: "/assets/images/whatsapp.svg"
    
contact_section:
  title: "Get ready. <br> Contact us!"
  address: "OneStep Licensing, <br> Kowloon, Hong Kong"
  form_action: "https://submit.jotform.com/submit/251855089016057"
  success_message: "Thank you. <br> Your message is sent successfully and we will contact you soon."
  submit_text: "SUBMIT"

collections:
  toys:
    output: true
    permalink: /toys/:name/
